version: '3.8'
services:
  redis:
    image: redis:6.2-alpine
    network_mode: host
    container_name: redis
    restart: always
    ports:
      - "6382:6379"
  db:
    image: postgres:14.1-alpine
    network_mode: host
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
